### PR TITLE
Added an ability to set a fixed version

### PR DESCRIPTION
**Pull request by akanderski**
Added an ability to set a fixed version.

### CODE REVIEW

**Comment by cmer** [comment]
Thanks! I will review shortly.

**Review by cmer — CHANGES_REQUESTED** [review]
It seems like this patch only works with the Community Edition. Please update to support Pro. Thanks!

**Comment by cmer** [comment]
I have just written a script that handles all editions. I'll update the image shortly with it.

**Comment by akanderski** [comment]
Thanks! I did not consider PRO version. Simply because I do not use it.

**Comment by cmer** [comment]
I updated `master` with this feature. Let me know if it works for you.

**Pull request closed without merging**
